"""Add 'searched' column to SEARCHES_REFERENCE table

Revision ID: 1207ff76fca1
Revises: 6e307a1b5e62
Create Date: 2023-06-05 22:04:02.583475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1207ff76fca1'
down_revision = '6e307a1b5e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SEARCHES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('searched', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SEARCHES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_column('searched')

    # ### end Alembic commands ###
