"""Add search_id to Article

Revision ID: 3c85270fe132
Revises: 7012c4fe7a4e
Create Date: 2023-06-14 20:19:26.817148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c85270fe132'
down_revision = '7012c4fe7a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_constraint('search_id', type_='foreignkey')
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('search_id', 'SEARCHES_REFERENCE', ['search_id'], ['id'])

    # ### end Alembic commands ###
