"""Add 'analyzed' column to SEARCHES_REFERENCE table

Revision ID: 43d1b6d21278
Revises: 1207ff76fca1
Create Date: 2023-06-06 21:31:30.947134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d1b6d21278'
down_revision = '1207ff76fca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SEARCHES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyzed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SEARCHES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_column('analyzed')

    # ### end Alembic commands ###
