"""Changed search_id to search_ids. Will reverse

Revision ID: 6e95c8389d3b
Revises: afe42ccf1842
Create Date: 2023-06-14 21:11:32.335200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e95c8389d3b'
down_revision = 'afe42ccf1842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_ids', sa.Integer(), nullable=True))
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('search_ids')

    # ### end Alembic commands ###
