"""Add search_id foreign key to Article

Revision ID: 7012c4fe7a4e
Revises: 43d1b6d21278
Create Date: 2023-06-13 20:26:59.685117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7012c4fe7a4e'
down_revision = '43d1b6d21278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('search_id', 'SEARCHES_REFERENCE', ['search_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_constraint('search_id', type_='foreignkey')
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###
