"""removed nullable property of Article's search_id

Revision ID: 9aa1ce9d3159
Revises: 6e95c8389d3b
Create Date: 2023-06-14 21:48:58.838225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa1ce9d3159'
down_revision = '6e95c8389d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))
        batch_op.drop_column('search_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_ids', sa.INTEGER(), nullable=True))
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###
