"""Add search_id to Verb, Article, Entity

Revision ID: afe42ccf1842
Revises: 3c85270fe132
Create Date: 2023-06-14 20:22:23.742907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe42ccf1842'
down_revision = '3c85270fe132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('ENTITIES_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('VERBS_REFERENCE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('VERBS_REFERENCE', schema=None) as batch_op:
        batch_op.drop_column('search_id')

    with op.batch_alter_table('ENTITIES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_column('search_id')

    with op.batch_alter_table('ARTICLES_REFERENCE', schema=None) as batch_op:
        batch_op.drop_column('search_id')

    # ### end Alembic commands ###
